FROM alpine:3.11 as builder

COPY . /nanomq

RUN apk add gcc cmake make musl-dev g++

WORKDIR /nanomq/build

RUN cmake -DNOLOG=1 .. && make install

FROM alpine:3.11

COPY --from=builder /nanomq/build/nanomq /usr/local/nanomq
COPY --from=builder /usr/lib/libgcc_s.so.1 /usr/lib/
COPY deploy/docker/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

WORKDIR /usr/local/nanomq

RUN ln -s /usr/local/nanomq/nanomq /usr/bin/nanomq

EXPOSE 1883

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

CMD ["--url", "nmq-tcp://0.0.0.0:1883"]
