FROM gcc:15 AS builder

COPY . /nanomq

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake libmbedtls-dev libssl-dev libtool pkg-config build-essential autoconf automake g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/zeromq

RUN wget https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz \
    && tar zxf zeromq-4.3.4.tar.gz \
    && cd zeromq-4.3.4 \
    && mkdir build \
    && cd build \
    && cmake -DBUILD_SHARED=OFF   \
    -DZMQ_BUILD_TESTS=OFF  \
    -DENABLE_CPACK=OFF  \
    -DWITH_DOC=OFF \
    -DCMAKE_BUILD_TYPE=Release .. \
    && make install 

WORKDIR /nanomq/build

RUN cmake -DENABLE_JWT=ON \
    -DNNG_ENABLE_TLS=ON \
    -DNNG_ENABLE_QUIC=ON \
    -DQUIC_BUILD_SHARED=OFF \
    -DQUIC_USE_SYSTEM_LIBCRYPTO=ON \
    -DNNG_ENABLE_SQLITE=ON \
    -DBUILD_ZMQ_GATEWAY=ON \
    -DBUILD_BENCH=ON .. \
    && make

FROM debian:11-slim

WORKDIR /usr/local/nanomq

COPY --from=builder /nanomq/build/nanomq/nanomq /usr/local/nanomq/
COPY --from=builder /nanomq/build/nanomq_cli/nanomq_cli /usr/local/nanomq/
COPY etc/nanomq.conf /etc/nanomq.conf
COPY etc/nanomq_gateway.conf /etc/nanomq_gateway.conf 
COPY deploy/docker/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

RUN ln -s /usr/local/nanomq/nanomq /usr/bin/nanomq && \
    ln -s /usr/local/nanomq/nanomq_cli /usr/bin/nanomq_cli

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libatomic1 && rm -rf /var/lib/apt/lists/*

EXPOSE 1883 8883 8081

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
