FROM xuesengxinyi/parquet-cross-compile-static:ubuntu18.04


# COPY NanoMQ_mirror 源代码
 WORKDIR /opt
 COPY ../.. ./NanoMQ_mirror/

# 编译 nanomq
WORKDIR /opt/NanoMQ_mirror
RUN mkdir build && cd build && cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                                    -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                                    -DBUILD_STATIC=ON \
                                    -DENABLE_PARQUET=ON  \
                                    -DNNG_ENABLE_TLS=ON \
                                    -DENABLE_FILETRANSFER=ON \
                                    -DCMAKE_FIND_ROOT_PATH=/usr/lib/aarch64-linux-gnu/\
                                    -DNNG_TESTS=OFF .. && make -j8 && make install

RUN mkdir build-debug && cd build-debug && cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                                            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                                            -DENABLE_PARQUET=ON  \
                                            -DNNG_ENABLE_TLS=ON \
                                            -DENABLE_FILETRANSFER=ON \
                                            -DBUILD_STATIC=ON \
                                            -DDEBUG=ON \
                                            -DASAN=OFF \
                                            -DCMAKE_FIND_ROOT_PATH=/usr/lib/aarch64-linux-gnu/ \
                                            -DNNG_TESTS=OFF .. && make -j8 && make install
