FROM ubuntu:18.04

# 安装基本工具和依赖
RUN apt-get update && \
    apt-get install -y build-essential curl && \
    apt-get install -y flex && \
    apt-get install -y bison && \
    apt-get install -y libboost-system-dev && \
    apt-get install -y libboost-all-dev

# 下载 Python-3.6
WORKDIR /opt
COPY ./Python-3.6.3.tgz .
RUN tar xf Python-3.6.3.tgz && \
    rm Python-3.6.3.tgz

# 下载 mbedtls 源代码
COPY ./mbedtls.tar.gz .
RUN tar xf mbedtls.tar.gz&& \
    rm mbedtls.tar.gz

# 下载 openssl 源代码
WORKDIR /opt
COPY ./openssl-1.1.1k.tar.gz .
RUN tar xf openssl-1.1.1k.tar.gz && \
    rm openssl-1.1.1k.tar.gz

# 下载 thrift 源代码
WORKDIR /opt
COPY ./thrift ./thrift


# 下载 parquet 源代码
WORKDIR /opt
COPY ./arrow ./arrow

# 下载 cmake
WORKDIR /opt
COPY ./cmake ./cmake
ENV PATH=$PATH:/opt/cmake/bin/

# 编译 Openssl
WORKDIR /opt/openssl-1.1.1k
RUN  ./Configure linux-x86_64 -fPIC no-shared &&\
     make -j32 &&\
     make install

# 编译 Python3.6
WORKDIR /opt/Python-3.6.3
RUN ./configure && make -j 32 && make install
RUN pip3.6 install jsonschema
RUN pip3.6 install jinja2

# 编译 mbedtls
WORKDIR /opt/mbedtls
RUN mkdir build && cd build &&\
    cmake -DENABLE_TESTING=OFF .. &&\
    make -j32 &&  make install

# 编译 thrift
WORKDIR /opt/thrift/build
RUN  cmake -DBUILD_CPP=on \
         -DBUILD_COMPILER=on \
         -DBUILD_TESTING=off \
         -DBUILD_C_GLIB=off \
         -DBUILD_AS3=off \
         -DBUILD_JAVA=off \
         -DBUILD_JAVASCRIPT=off \
         -DBUILD_NODEJS=off \
         -DBUILD_PYTHON=off \
         -DBUILD_HASKELL=off \
         -DWITH_QT5=off \
         -DWITH_OPENSSL=on \
         .. && make -j32 && make install
         
# 编译 parquet
WORKDIR /opt/arrow/cpp
RUN mkdir build && cd build &&\
    cmake -DARROW_PARQUET=ON  \
        -DARROW_BUILD_SHARED=OFF\
        -DARROW_WITH_BROTLI=ON \
	    -DARROW_WITH_BZ2=ON \
	    -DARROW_WITH_LZ4=ON \
	    -DARROW_WITH_SNAPPY=ON \
	    -DARROW_WITH_ZLIB=ON \
        -DARROW_JEMALLOC=OFF\
	    -DARROW_WITH_ZSTD=ON \
        -DARROW_USE_OPENSSL=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON\
        .. && make -j32 && make install

