FROM ubuntu:18.04

# 安装基本工具和依赖
RUN apt-get update && \
    apt-get install -y build-essential curl && \
    apt-get install -y flex && \
    apt-get install -y bison && \
    apt-get install -y libboost-system-dev && \
    apt-get install -y libboost-all-dev && \
    apt-get install -y libssl-dev &&\
    apt-get install -y openssl



# 下载 thrift 源代码
WORKDIR /opt
COPY ./thrift ./thrift


# 下载 parquet 源代码
WORKDIR /opt
COPY ./arrow ./arrow

# 下载 cmake
WORKDIR /opt
COPY ./cmake ./cmake
ENV PATH=$PATH:/opt/cmake/bin/

# 编译 thrift
WORKDIR /opt/thrift/build
RUN  cmake -DBUILD_CPP=on \
         -DBUILD_COMPILER=on \
         -DBUILD_TESTING=off \
         -DBUILD_C_GLIB=off \
         -DBUILD_AS3=off \
         -DBUILD_JAVA=off \
         -DBUILD_JAVASCRIPT=off \
         -DBUILD_NODEJS=off \
         -DBUILD_PYTHON=off \
         -DBUILD_HASKELL=off \
         -DWITH_QT5=off \
         -DWITH_OPENSSL=on \
         .. && make -j32 && make install
         
# 编译 parquet
WORKDIR /opt/arrow/cpp
RUN mkdir build && cd build &&\
    cmake -DARROW_PARQUET=ON  \
        -DARROW_BUILD_SHARED=OFF\
        -DARROW_WITH_BROTLI=ON \
	    -DARROW_WITH_BZ2=ON \
	    -DARROW_WITH_LZ4=ON \
	    -DARROW_WITH_SNAPPY=ON \
	    -DARROW_WITH_ZLIB=ON \
        -DARROW_JEMALLOC=OFF\
	    -DARROW_WITH_ZSTD=ON \
        -DARROW_USE_OPENSSL=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON\
        .. && make -j32 && make install

